/// <reference types="vitest" />
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import LevelsScreen from '../LevelsScreen'
import { useLevels } from '../../hooks/useLevels'

vi.mock('../../hooks/useLevels', () => ({ useLevels: vi.fn() }))
const mockUseLevels = vi.mocked(useLevels)
const a1 = { id: 'a1', code: 'A1', name: 'A1', version: 1, min_score: 0, max_score: 20, description: 'Basic', is_active: true }
const a2 = { id: 'a2', code: 'A2', name: 'A2', version: 1, min_score: 21, max_score: 100, description: 'Elementary', is_active: true }
const historical = { ...a1, id: 'old', version: 1, is_active: false }
const base = () => ({ levels: [a1, a2, historical], activeDistribution: { revision: 4, levels: [{ id: 'a1', min_score: 0, max_score: 20 }, { id: 'a2', min_score: 21, max_score: 100 }] }, loading: false, error: null, updateLevelMetadata: vi.fn().mockResolvedValue({ data: a1, error: null }), replaceActiveLevelDistribution: vi.fn().mockResolvedValue({ data: { revision: 5 }, error: null }), refetch: vi.fn() })

beforeEach(() => { vi.clearAllMocks(); mockUseLevels.mockReturnValue(base()) })
const renderScreen = () => render(<LevelsScreen />)

describe('LevelsScreen', () => {
  it('orders levels and shows active and historical states', () => { renderScreen(); expect(screen.getAllByText('A1').length).toBeGreaterThan(1); expect(screen.getAllByText('Active').length).toBe(2); expect(screen.getByText('Historical version — retained for existing records')).toBeInTheDocument() })
  it('shows the complete before/after distribution editor', () => { renderScreen(); fireEvent.click(screen.getByText('Edit distribution')); expect(screen.getByText('Before: 0–20 · After: 0–20')).toBeInTheDocument(); expect(screen.getByText('Before: 21–100 · After: 21–100')).toBeInTheDocument() })
  it('validates locally and does not send an invalid distribution', () => { const hooks = base(); mockUseLevels.mockReturnValue(hooks); renderScreen(); fireEvent.click(screen.getByText('Edit distribution')); fireEvent.change(screen.getByLabelText('Maximum score A1'), { target: { value: '30' } }); fireEvent.submit(screen.getByRole('button', { name: 'Save' }).closest('form')!); expect(screen.getByText(/whole-number ranges/)).toBeInTheDocument(); expect(hooks.replaceActiveLevelDistribution).not.toHaveBeenCalled() })
  it('confirms once and sends the full distribution in one RPC', async () => { const hooks = base(); mockUseLevels.mockReturnValue(hooks); vi.spyOn(window, 'confirm').mockReturnValue(true); renderScreen(); fireEvent.click(screen.getByText('Edit distribution')); fireEvent.change(screen.getByLabelText('Maximum score A1'), { target: { value: '30' } }); fireEvent.change(screen.getByLabelText('Minimum score A2'), { target: { value: '31' } }); fireEvent.submit(screen.getByRole('button', { name: 'Save' }).closest('form')!); await waitFor(() => expect(hooks.replaceActiveLevelDistribution).toHaveBeenCalledTimes(1)); expect(hooks.replaceActiveLevelDistribution).toHaveBeenCalledWith({ expected_revision: 4, levels: [{ id: 'a1', min_score: 0, max_score: 30 }, { id: 'a2', min_score: 31, max_score: 100 }] }) })
  it('reloads without stale editor state after a conflict', async () => { const hooks = base(); hooks.replaceActiveLevelDistribution = vi.fn().mockResolvedValue({ data: null, error: 'stale', code: '40001', conflict: true }); mockUseLevels.mockReturnValue(hooks); vi.spyOn(window, 'confirm').mockReturnValue(true); renderScreen(); fireEvent.click(screen.getByText('Edit distribution')); fireEvent.submit(screen.getByRole('button', { name: 'Save' }).closest('form')!); await waitFor(() => expect(screen.getByText(/changed elsewhere/)).toBeInTheDocument()); expect(hooks.refetch).toHaveBeenCalled() ; expect(screen.queryByText('Active score distribution')).not.toBeInTheDocument() })
  it('preserves metadata editing and deactivates a boundary through one full RPC', async () => { const hooks = base(); mockUseLevels.mockReturnValue(hooks); vi.spyOn(window, 'confirm').mockReturnValue(true); renderScreen(); fireEvent.click(screen.getAllByText('Edit details')[0]); fireEvent.change(screen.getByLabelText('Name'), { target: { value: 'Starter' } }); fireEvent.submit(screen.getByRole('button', { name: 'Save' }).closest('form')!); await waitFor(() => expect(hooks.updateLevelMetadata).toHaveBeenCalledWith(expect.objectContaining({ name: 'Starter' }))); fireEvent.click(screen.getAllByText('Deactivate')[0]); expect(screen.getByText('Removed from active distribution: 0–20')).toBeInTheDocument(); expect(screen.getByText('Before: 21–100 · After: 0–100')).toBeInTheDocument(); fireEvent.submit(screen.getByRole('button', { name: 'Save' }).closest('form')!); await waitFor(() => expect(hooks.replaceActiveLevelDistribution).toHaveBeenCalledTimes(1)); expect(hooks.replaceActiveLevelDistribution).toHaveBeenCalledWith({ expected_revision: 4, levels: [{ id: 'a2', min_score: 0, max_score: 100 }], deactivate_level_id: 'a1' }); expect(screen.getByText('The level was deactivated.')).toBeInTheDocument() })

  it('previews middle and odd redistribution with the extra point assigned upward', () => { const hooks = base(); const b = { ...a2, id: 'b', name: 'B', min_score: 21, max_score: 41 }; const c = { ...a2, id: 'c', name: 'C', min_score: 42, max_score: 100 }; hooks.levels = [a1, b, c]; hooks.activeDistribution = { revision: 7, levels: [a1, b, c].map(({ id, min_score, max_score }) => ({ id, min_score, max_score })) }; mockUseLevels.mockReturnValue(hooks); renderScreen(); fireEvent.click(screen.getAllByText('Deactivate')[1]); expect(screen.getByText('Before: 0–20 · After: 0–30')).toBeInTheDocument(); expect(screen.getByText('Before: 42–100 · After: 31–100')).toBeInTheDocument() })
})
